const { PHASE_DEVELOPMENT_SERVER } = require('next/constants')

module.exports = (phase, { defaultConfig }) => {
  return {
    "env": {
      "SERVER_SESSION_SECRET": process.env.SERVER_SESSION_SECRET,
      "SERVER_FIREBASE_PROJECT_ID": process.env.SERVER_FIREBASE_PROJECT_ID,
      "SERVER_FIREBASE_PRIVATE_KEY_ID": process.env.SERVER_FIREBASE_PRIVATE_KEY_ID,
      "SERVER_FIREBASE_PRIVATE_KEY_BASE64": process.env.SERVER_FIREBASE_PRIVATE_KEY_BASE64,
      "SERVER_FIREBASE_CLIENT_EMAIL": process.env.SERVER_FIREBASE_CLIENT_EMAIL,
      "SERVER_FIREBASE_CLIENT_ID": process.env.SERVER_FIREBASE_CLIENT_ID,
      "SERVER_FIREBASE_AUTH_URI": process.env.SERVER_FIREBASE_AUTH_URI,
      "SERVER_FIREBASE_TOKEN_URI": process.env.SERVER_FIREBASE_TOKEN_URI,
      "SERVER_FIREBASE_AUTH_PROVIDER_X509_CERT_URL": process.env.SERVER_FIREBASE_AUTH_PROVIDER_X509_CERT_URL,
      "SERVER_FIREBASE_CLIENT_X509_CERT_URL": process.env.SERVER_FIREBASE_CLIENT_X509_CERT_URL,
      "CLIENT_FIREBASE_API_KEY": process.env.CLIENT_FIREBASE_API_KEY,
      "CLIENT_FIREBASE_AUTH_DOMAIN": process.env.CLIENT_FIREBASE_AUTH_DOMAIN,
      "CLIENT_FIREBASE_DATABASE_URL": process.env.CLIENT_FIREBASE_DATABASE_URL,
      "CLIENT_FIREBASE_PROJECT_ID": process.env.CLIENT_FIREBASE_PROJECT_ID,
      "CLIENT_FIREBASE_STORAGE_BUCKET": process.env.CLIENT_FIREBASE_STORAGE_BUCKET,
      "CLIENT_FIREBASE_MESSAGING_SENDER_ID": process.env.CLIENT_FIREBASE_MESSAGING_SENDER_ID,
      "CLIENT_FIREBASE_APP_ID": process.env.CLIENT_FIREBASE_APP_ID,
    }
  }
}
